import Head from 'next/head';
// import Image from 'next/image';
// import { Inter } from 'next/font/google';
// import ExampleHero from '../components/hero/example';
// import Hero1 from '@/components/hero/hero1';
// import Hero2 from '@/components/hero/hero2';
// import TopBanner from '@/components/hero/top_banner';

import api_client from '@/components/api/api_client';
// const inter = Inter({ subsets: ['latin'] });

import BaseModal from '@/components/booking_modal/base';
import Banner from '@/components/static/banner';
import Banner2 from '@/components/static/banner2';
import Banner3 from '@/components/static/banner3';
import Banner4 from '@/components/static/banner4';
import Banner5 from '@/components/static/banner5';

export default function Home(props) {
  // console.log('modal', props.serviceMap);
    // console.log('booking data', props);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BaseModal 
        theatres={props.theatres}
        serviceMap={props.serviceMap}
      />
      
      <Banner />

      <main id="main">
          <Banner2 />
          <Banner3 />
          <Banner4 />
          <Banner5 />
          
      </main>
    </>
  )
}

export async function getServerSideProps(ctx){
  console.log();
  const [theatres, services, serviceDetails] = await Promise.all([
      api_client.getTheatres(),
      api_client.getServices(),
      api_client.getServiceDetails(),
    ]);

  const serviceMap = {};
  for (let i=0; i<services.data.length; i++) {
      serviceMap[services.data[i].attributes.name] = [];
  }
  for (let i=0; i<serviceDetails.data.length; i++) {
      serviceMap[serviceDetails.data[i].attributes.service.data.attributes.name].push({
          id: serviceDetails.data[i].id,
          ...serviceDetails.data[i].attributes,
      });
  }

  // console.log(serviceMap);

  return {
      props:{
          theatres: theatres,
          serviceMap: serviceMap
      }
  }
}
