import { useRouter } from 'next/router';
import Head from 'next/head';
import { useEffect } from 'react';
import { useData } from '../context/sip_context';

function ThankYou(props) {
    const router = useRouter();
    const { data } = useData();
    const services = ['decorations', 'cake', 'extra-decorations', 'flowers', 'photography'];
    console.log('thankyou', data);

    useEffect(() => {
        // This will only run on the client side
        if (!data) {
            console.log('Initiate booking first!');
            router.push('/');
        }
      }, [router]);

    const extra_seats = data != null && data.booking.total_seats_booked > data.theater.attributes.num_seats ? data.booking.total_seats_booked-data.theater.attributes.num_seats : 0;

    if (!data) {
        return <>Loading...</>;
    }
    return (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
      </Head>

    <main id="main">
    <section id="stats-counter " className="stats-counter thankyou">
      <div className="container" data-aos="fade-up">
        <div className="section-header">
          <h2>Thank You</h2>
          <p>
          Hi {data.booking.customer_name}, Your booking is confirmed on {data.booking.date}.
          <br/>Checkout the details
          </p>
          
          <table className="table table-striped">
            <thead>
              <tr>
                <th>Description</th>
                <th>Amount</th>
              </tr>
            </thead>
            <tbody>
            <tr>
                <td>Theatre ({data.theater.attributes.name})</td>
                <td>{data.theater.attributes.pricing_per_slot}</td>
            </tr>
            <tr>
                <td>Advance Paid</td>
                <td>{data.booking.price_paid}</td>
            </tr>
            <tr>
                <td>Total Seats booked - {data.result.attributes.total_seats_booked}</td>
                <td></td>
            </tr>
            {extra_seats > 0 && 
            <tr>
                <td>Extra Seats booked - {extra_seats}</td>
                <td>{extra_seats * data.theater.attributes.extra_seat_cost}</td>
            </tr>
            }
            {Object.entries(data.serviceMap['cake']).map(([key, value]) => {
                    return <tr>
                      <td>cake - {value.name}</td>
                      <td>{value.price}</td>
                    </tr>
                  })
            }
            {Object.entries(data.serviceMap['decorations']).map(([key, value]) => {
                    return <tr>
                      <td>Celebration - {value.name}</td>
                      <td>{value.price}</td>
                    </tr>
                  })
            }
            {Object.entries(data.serviceMap['extra-decorations']).map(([key, value]) => {
                    return <tr>
                      <td>Addon - {value.name}</td>
                      <td>{value.price}</td>
                    </tr>
                  })
            }
            {Object.entries(data.serviceMap['flowers']).map(([key, value]) => {
                    return <tr>
                      <td>Flowers - {value.name}</td>
                      <td>{value.price}</td>
                    </tr>
                  })
            }
            {Object.entries(data.serviceMap['photography']).map(([key, value]) => {
                    return <tr>
                      <td>Photography - {value.name}</td>
                      <td>{value.price}</td>
                    </tr>
                  })
            }
              <tr>
                <td>celebration</td>
                <td>1000</td>
              </tr>
              <tr>
                <td>Cakes </td>
                <td>1000</td>
              </tr>
                <tr>
                  <td>4</td>
                  <td>Extra Decoration  </td>
                  <td>1000</td>
                </tr>
                  <tr>
                    <td>5</td>
                    <td>Roses </td>
                    <td>1000</td>
                  </tr>
                    <tr>
                      <td>6</td>
                      <td>Extra Decoration 
                        Smoke
                        Balloons
                        music
                         </td>
                      <td>1000</td>
                    </tr>
                      <tr>
                        <td>7</td>
                        <td>Memories
                          100 pics 
                           </td>
                        <td>1000</td>
                      </tr>
                <tr>
                <th colspan="2">Total </th>
                <th>5000/-</th>
              </tr>
            </tbody>
            </table>
        </div>
    
      </div>
    </section>
    </main>
    </>
    );
}

export default ThankYou;